#!/usr/bin/env python3
"""
Build deadline_tool.html — the trade-deadline analyzer.

A from-scratch replacement for trade_tool.html (which was generated by patching
draft_tool.html). Same core methodology, new data, new UI:

- Hitter projections: TheBat_RoS_ASB.csv (The Bat, rest-of-season as of the
  All-Star break). Weekly rates are computed on a ROS-CORRECT time base:
  full-time ROS playing time at the ASB is ~275 PA over ~11 MLB weeks, so
  TARGET_PA=275 and ROS_WEEKS=11 (= 25 PA/week, identical weekly framing to the
  draft tool). Players below TARGET_PA are supplemented with replacement-level
  production for the missing PA, exactly like create_league_stats.py.

  NOTE: this fixes a real flaw in build_trade_tool.py, which kept the
  full-season TARGET_PA=625 / NUM_WEEKS=25 while feeding it ROS projections.
  With ASB data (max ~290 PA) that would have blended EVERY player ~55%
  toward replacement, crushing the spread between stars and scrubs.

- Pitcher projections: reused from the PITCHERS array embedded in
  trade_tool.html (ATC preseason, already expressed as blended weekly rates).
  They are STALE (no ROS pitching file exists in the repo) — the UI labels
  them accordingly. Drop a ROS pitching CSV in and extend this script to
  refresh them.

- Rosters/owners/positions: rosters_May.csv (latest Fantrax export in repo).
  Owned hitters missing from the projection file are synthesized at
  replacement level (flagged `synth`) so rosters stay complete and they remain
  valid drop candidates.

Usage:  python3 build_deadline_tool.py
Output: deadline_tool.html (self-contained, open in any browser)
"""

import csv
import json
import unicodedata
from datetime import date

HITTERS_CSV = "TheBat_RoS_ASB.csv"
ROSTERS_CSV = "rosters_May.csv"
PITCHERS_SOURCE_HTML = "trade_tool.html"   # PITCHERS array is lifted from here
TEMPLATE = "deadline_tool_template.html"
OUT_HTML = "deadline_tool.html"

MY_TEAM = "Skrey"
TEAM_NAMES = [
    "Skrey", "JDM", "BigJoe", "Ferrante", "Rut", "Gwon", "Beefs", "Unks",
    "Swagga", "Triz", "Boofers", "Shmoulie", "DertyDer", "wes11",
    "DGreasy", "Diarrhea",
]

# ---- ROS time base (see module docstring) ----
TARGET_PA = 275        # full-time ROS PA at the ASB (file max is ~290)
ROS_WEEKS = TARGET_PA / 25.0   # keeps the 25 PA/week framing => 11.0
MIN_FA_PA = 60         # FA hitters below this ROS PA are noise; owned ones kept

# Replacement per-PA rates (DC ranks 155-175 cohort, from create_league_stats.py)
REP = dict(r=0.121162, hr=0.033035, rbi=0.120773, so=0.222623,
           tb=0.372522, sb=0.015157, obp=0.324)

# League weekly SD / AVG (34% 2024 + 66% 2025 filtered) — for the value z-proxy
SD = dict(r=6.02, hr=3.04, rbi=6.89, sb=2.57, so=7.96, tb=15.98, obp=0.0351)
AVG_OBP = 0.327

HITTER_SLOTS = ('C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF', 'UT')


def normalize(name):
    nfkd = unicodedata.normalize('NFKD', name)
    n = ''.join(c for c in nfkd if not unicodedata.combining(c)).lower().strip()
    n = n.replace("'", "").replace("’", "").replace("-", " ")
    n = n.replace(".", "").replace(",", "")
    return ' '.join(n.split())


def extract_json_array(content, prefix):
    idx = content.find(prefix)
    if idx == -1:
        raise ValueError(f"Could not find '{prefix}'")
    start = content.find('[', idx)
    depth = 0
    for i, c in enumerate(content[start:], start):
        if c == '[':
            depth += 1
        elif c == ']':
            depth -= 1
        if depth == 0:
            return json.loads(content[start:i + 1])
    raise ValueError("Unbalanced array")


def weekly_hitter(name, mlb, pa, r, hr, rbi, so, tb, sb, obp, synth=False):
    """Supplement to TARGET_PA at replacement rates, convert to weekly."""
    if pa < TARGET_PA:
        gap = TARGET_PA - pa
        r += gap * REP['r']; hr += gap * REP['hr']; rbi += gap * REP['rbi']
        so += gap * REP['so']; tb += gap * REP['tb']; sb += gap * REP['sb']
        obp = (pa * obp + gap * REP['obp']) / TARGET_PA
    w = lambda x: x / ROS_WEEKS
    value = (w(r) / SD['r'] + w(hr) / SD['hr'] + w(rbi) / SD['rbi']
             + w(sb) / SD['sb'] + w(tb) / SD['tb'] - w(so) / SD['so']
             + (obp - AVG_OBP) / 9 / SD['obp'])
    return {
        'name': name, 'mlb': mlb, 'pa': int(round(pa)),
        'r': round(w(r), 3), 'hr': round(w(hr), 3), 'rbi': round(w(rbi), 3),
        'so': round(w(so), 3), 'tb': round(w(tb), 3), 'sb': round(w(sb), 3),
        'obp': round(obp, 3), 'value': round(value, 4),
        **({'synth': True} if synth else {}),
    }


def read_rosters():
    """First occurrence per normalized name (CSV is RkOv-sorted, so the MLB
    player beats any minor-league name twin). Returns (owner, positions) maps
    keyed by normalized name, plus the raw rows for roster building."""
    owner, positions, rows = {}, {}, []
    with open(ROSTERS_CSV) as f:
        for row in csv.DictReader(f):
            n = normalize(row['Player'])
            if n in owner:
                continue
            owner[n] = row['Status']
            positions[n] = [p for p in row['Position'].split(',') if p in HITTER_SLOTS]
            rows.append(row)
    return owner, positions, rows


def build_hitters(owner, positions):
    hitters, seen = [], set()
    kept_fa = skipped_fa = 0
    with open(HITTERS_CSV, encoding='utf-8-sig') as f:
        for row in csv.DictReader(f):
            name = row['Name']
            n = normalize(name)
            pa = float(row['PA'])
            own = owner.get(n, 'FA')
            if own == 'FA':
                if pa < MIN_FA_PA:
                    skipped_fa += 1
                    continue
                kept_fa += 1
            tb = (float(row['1B']) + 2 * float(row['2B'])
                  + 3 * float(row['3B']) + 4 * float(row['HR']))
            h = weekly_hitter(name, row['Team'], pa, float(row['R']),
                              float(row['HR']), float(row['RBI']),
                              float(row['SO']), tb, float(row['SB']),
                              float(row['OBP']))
            h['pos'] = positions.get(n, ['UT'])
            hitters.append(h)
            seen.add(n)
    print(f"  hitters: {len(hitters)} kept ({kept_fa} FA), {skipped_fa} low-PA FA skipped")
    return hitters, seen


def synthesize_missing_owned(hitters, seen, owner, positions, roster_rows):
    """Owned hitters absent from the projection file get a replacement-level
    line so their roster spot (and drop-candidate status) isn't lost."""
    for row in roster_rows:
        if row['Status'] == 'FA' or row['Status'] not in TEAM_NAMES:
            continue
        n = normalize(row['Player'])
        pos = positions.get(n, [])
        if not pos or n in seen:
            continue
        if row['Player'].endswith('-P'):
            continue
        name = row['Player'].removesuffix('-H')
        if normalize(name) in seen:
            continue
        h = weekly_hitter(name, row['Team'], 0, 0, 0, 0, 0, 0, 0, REP['obp'], synth=True)
        h['pos'] = pos
        hitters.append(h)
        seen.add(n)
        print(f"  synthesized replacement-level line for {name} ({row['Status']})")


def load_pitchers():
    with open(PITCHERS_SOURCE_HTML) as f:
        content = f.read()
    arr = extract_json_array(content, 'const PITCHERS = [')
    keep = ('name', 'type', 'ip_wk', 'l_wk', 'sv_wk', 'hld_wk', 'k_wk',
            'qs_wk', 'er_wk', 'wh_wk', 'era', 'whip', 'war', 'dualEligible')
    out = [{k: p[k] for k in keep if k in p} for p in arr]
    # Ohtani exists in BOTH pools (bat + arm). Disambiguate the pitcher half so
    # name-keyed maps (owners, MV) can never conflate the two.
    for p in out:
        if p['name'] == 'Shohei Ohtani':
            p['name'] = 'Shohei Ohtani (P)'
    print(f"  pitchers: {len(out)} (ATC preseason, reused from {PITCHERS_SOURCE_HTML})")
    return out


def build_rosters_and_owners(hitters, pitchers, roster_rows):
    """rosters: {team: [{name, type}]}, owners: {projName: team|'FA'}"""
    hit_by_norm = {normalize(h['name']): h['name'] for h in hitters}
    pit_by_norm = {normalize(p['name']): p['name'] for p in pitchers}
    rosters = {t: [] for t in TEAM_NAMES}
    owners = {}
    skipped = []
    for row in roster_rows:
        fx, team, pos = row['Player'], row['Status'], row['Position'].split(',')
        if fx == 'Shohei Ohtani-H':
            fx = 'Shohei Ohtani'
        elif fx == 'Shohei Ohtani-P':
            fx = 'Shohei Ohtani (P)'
        n = normalize(fx)
        has_bat = any(p in HITTER_SLOTS for p in pos)
        has_arm = any(p in ('SP', 'RP') for p in pos)
        if has_bat and n in hit_by_norm:
            name = hit_by_norm[n]
            owners[name] = team
            if team in rosters:
                rosters[team].append({'name': name, 'type': 'H'})
        elif has_arm and n in pit_by_norm:
            name = pit_by_norm[n]
            owners[name] = team
            if team in rosters:
                rosters[team].append({'name': name, 'type': 'SP' if 'SP' in pos else 'RP'})
        elif team in rosters:
            skipped.append((fx, team))
    if skipped:
        print(f"  {len(skipped)} owned players have no projection (prospects/stale arms):")
        for nm, t in skipped:
            print(f"    {nm} ({t})")
    return rosters, owners


def main():
    print("Reading rosters...")
    owner, positions, roster_rows = read_rosters()

    print("Building ASB ROS hitter projections...")
    hitters, seen = build_hitters(owner, positions)
    synthesize_missing_owned(hitters, seen, owner, positions, roster_rows)

    print("Loading pitchers...")
    pitchers = load_pitchers()

    overlap = {h['name'] for h in hitters} & {p['name'] for p in pitchers}
    if overlap:
        raise RuntimeError(f"Name collision between hitter and pitcher pools: {overlap}")

    print("Assembling rosters...")
    rosters, owners = build_rosters_and_owners(hitters, pitchers, roster_rows)
    for t in TEAM_NAMES:
        nH = sum(1 for p in rosters[t] if p['type'] == 'H')
        nP = len(rosters[t]) - nH
        print(f"    {t:10s} {nH:2d} H / {nP:2d} P")

    data = {
        'MY_TEAM': MY_TEAM,
        'TEAM_NAMES': TEAM_NAMES,
        'HITTERS': hitters,
        'PITCHERS': pitchers,
        'ROSTERS': rosters,
        'OWNERS': owners,
        'META': {
            'built': date.today().isoformat(),
            'hitterSource': 'The Bat ROS (All-Star break)',
            'pitcherSource': 'ATC preseason (stale — no ROS pitching file)',
            'rosterSource': 'rosters_May.csv',
            'targetPA': TARGET_PA,
            'rosWeeks': ROS_WEEKS,
        },
    }

    with open(TEMPLATE) as f:
        html = f.read()
    payload = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    html = html.replace('/*__DATA__*/null', payload, 1)

    with open(OUT_HTML, 'w') as f:
        f.write(html)
    print(f"Wrote {OUT_HTML} ({len(html)//1024} KB)")


if __name__ == '__main__':
    main()
